books_category:
    resource: "@BooksBundle/Controller/CategoryController.php"
    type:     annotation

books_book:
    resource: "@BooksBundle/Controller/BookController.php"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
books:
    resource: "@BooksBundle/Controller/"
    type:     annotation
